/*
 * UAVCAN data structure definition for libcanard.
 *
 * Autogenerated, do not edit.
 *
 */

#ifndef __DSDL_UAVCAN_PROTOCOL_PARAM_EMPTY
#define __DSDL_UAVCAN_PROTOCOL_PARAM_EMPTY

#include <uavcan_service/libcanard/canard.h>

#ifdef __cplusplus
extern "C"
{
#endif

/******************************* Source text **********************************
#
# Ex nihilo nihil fit.
#
******************************************************************************/

/********************* DSDL signature source definition ***********************
dsdl.uavcan.protocol.param.Empty
******************************************************************************/

#define DSDL_UAVCAN_PROTOCOL_PARAM_EMPTY_NAME              "dsdl.uavcan.protocol.param.Empty"
#define DSDL_UAVCAN_PROTOCOL_PARAM_EMPTY_SIGNATURE         (0xD3A71B5D0453E372ULL)

#define DSDL_UAVCAN_PROTOCOL_PARAM_EMPTY_MAX_SIZE          ((0 + 7)/8)

typedef struct
{
    uint8_t empty;
} dsdl_uavcan_protocol_param_Empty;

static inline
uint32_t dsdl_uavcan_protocol_param_Empty_encode(dsdl_uavcan_protocol_param_Empty* source, void* msg_buf);

static inline
int32_t dsdl_uavcan_protocol_param_Empty_decode(const CanardRxTransfer* transfer, uint16_t payload_len, dsdl_uavcan_protocol_param_Empty* dest, uint8_t** dyn_arr_buf);

static inline
uint32_t dsdl_uavcan_protocol_param_Empty_encode_internal(dsdl_uavcan_protocol_param_Empty* source, void* msg_buf, uint32_t offset, uint8_t root_item);

static inline
int32_t dsdl_uavcan_protocol_param_Empty_decode_internal(const CanardRxTransfer* transfer, uint16_t payload_len, dsdl_uavcan_protocol_param_Empty* dest, uint8_t** dyn_arr_buf, int32_t offset, uint8_t tao);


/*
 * UAVCAN data structure definition for libcanard.
 *
 * Autogenerated, do not edit.
 *
 */

#ifndef CANARD_INTERNAL_SATURATE
#define CANARD_INTERNAL_SATURATE(x, max) ( ((x) > max) ? max : ( (-(x) > max) ? (-max) : (x) ) );
#endif

#ifndef CANARD_INTERNAL_SATURATE_UNSIGNED
#define CANARD_INTERNAL_SATURATE_UNSIGNED(x, max) ( ((x) > max) ? max : (x) );
#endif

#define CANARD_INTERNAL_ENABLE_TAO  ((uint8_t) 1)
#define CANARD_INTERNAL_DISABLE_TAO ((uint8_t) 0)

#if defined(__GNUC__)
# define CANARD_MAYBE_UNUSED(x) x __attribute__((unused))
#else
# define CANARD_MAYBE_UNUSED(x) x
#endif

uint32_t dsdl_uavcan_protocol_param_Empty_encode_internal(dsdl_uavcan_protocol_param_Empty* CANARD_MAYBE_UNUSED(source),
  void* CANARD_MAYBE_UNUSED(msg_buf),
  uint32_t offset,
  uint8_t CANARD_MAYBE_UNUSED(root_item))
{
    return offset;
}

uint32_t dsdl_uavcan_protocol_param_Empty_encode(dsdl_uavcan_protocol_param_Empty* CANARD_MAYBE_UNUSED(source), void* CANARD_MAYBE_UNUSED(msg_buf))
{
    return 0;
}

int32_t dsdl_uavcan_protocol_param_Empty_decode_internal(const CanardRxTransfer* CANARD_MAYBE_UNUSED(transfer),
  uint16_t CANARD_MAYBE_UNUSED(payload_len),
  dsdl_uavcan_protocol_param_Empty* CANARD_MAYBE_UNUSED(dest),
  uint8_t** CANARD_MAYBE_UNUSED(dyn_arr_buf),
  int32_t offset,
  uint8_t CANARD_MAYBE_UNUSED(tao))
{
    return offset;
}

int32_t dsdl_uavcan_protocol_param_Empty_decode(const CanardRxTransfer* CANARD_MAYBE_UNUSED(transfer),
  uint16_t CANARD_MAYBE_UNUSED(payload_len),
  dsdl_uavcan_protocol_param_Empty* CANARD_MAYBE_UNUSED(dest),
  uint8_t** CANARD_MAYBE_UNUSED(dyn_arr_buf))
{
    return 0;
}

#ifdef __cplusplus
} // extern "C"
#endif
#endif // __DSDL_UAVCAN_PROTOCOL_PARAM_EMPTY