/*
 * UAVCAN data structure definition for libcanard.
 *
 * Autogenerated, do not edit.
 *
 */

#ifndef __DSDL_UAVCAN_PROTOCOL_DYNAMIC_NODE_ID_SERVER_ENTRY
#define __DSDL_UAVCAN_PROTOCOL_DYNAMIC_NODE_ID_SERVER_ENTRY

#include <uavcan_service/libcanard/canard.h>

#ifdef __cplusplus
extern "C"
{
#endif

/******************************* Source text **********************************
#
# THIS DEFINITION IS SUBJECT TO CHANGE.
#
# One dynamic node ID allocation entry.
# This type is a part of the Raft consensus algorithm.
# Please refer to the specification for details.
#

uint32 term             # Refer to the Raft paper for explanation.

uint8[16] unique_id     # Unique ID of this allocation.

void1
uint7 node_id           # Node ID of this allocation.
******************************************************************************/

/********************* DSDL signature source definition ***********************
dsdl.uavcan.protocol.dynamic_node_id.server.Entry
saturated uint32 term
saturated uint8[16] unique_id
void1
saturated uint7 node_id
******************************************************************************/

#define DSDL_UAVCAN_PROTOCOL_DYNAMIC_NODE_ID_SERVER_ENTRY_NAME "dsdl.uavcan.protocol.dynamic_node_id.server.Entry"
#define DSDL_UAVCAN_PROTOCOL_DYNAMIC_NODE_ID_SERVER_ENTRY_SIGNATURE (0x78A8B93604E8D68EULL)

#define DSDL_UAVCAN_PROTOCOL_DYNAMIC_NODE_ID_SERVER_ENTRY_MAX_SIZE ((168 + 7)/8)

// Constants

#define DSDL_UAVCAN_PROTOCOL_DYNAMIC_NODE_ID_SERVER_ENTRY_UNIQUE_ID_LENGTH               16

typedef struct
{
    // FieldTypes
    uint32_t   term;                          // bit len 32
    uint8_t    unique_id[16];                 // Static Array 8bit[16] max items
    // void1
    uint8_t    node_id;                       // bit len 7

} dsdl_uavcan_protocol_dynamic_node_id_server_Entry;

static inline
uint32_t dsdl_uavcan_protocol_dynamic_node_id_server_Entry_encode(dsdl_uavcan_protocol_dynamic_node_id_server_Entry* source, void* msg_buf);

static inline
int32_t dsdl_uavcan_protocol_dynamic_node_id_server_Entry_decode(const CanardRxTransfer* transfer, uint16_t payload_len, dsdl_uavcan_protocol_dynamic_node_id_server_Entry* dest, uint8_t** dyn_arr_buf);

static inline
uint32_t dsdl_uavcan_protocol_dynamic_node_id_server_Entry_encode_internal(dsdl_uavcan_protocol_dynamic_node_id_server_Entry* source, void* msg_buf, uint32_t offset, uint8_t root_item);

static inline
int32_t dsdl_uavcan_protocol_dynamic_node_id_server_Entry_decode_internal(const CanardRxTransfer* transfer, uint16_t payload_len, dsdl_uavcan_protocol_dynamic_node_id_server_Entry* dest, uint8_t** dyn_arr_buf, int32_t offset, uint8_t tao);

/*
 * UAVCAN data structure definition for libcanard.
 *
 * Autogenerated, do not edit.
 *
 */

#ifndef CANARD_INTERNAL_SATURATE
#define CANARD_INTERNAL_SATURATE(x, max) ( ((x) > max) ? max : ( (-(x) > max) ? (-max) : (x) ) );
#endif

#ifndef CANARD_INTERNAL_SATURATE_UNSIGNED
#define CANARD_INTERNAL_SATURATE_UNSIGNED(x, max) ( ((x) > max) ? max : (x) );
#endif

#define CANARD_INTERNAL_ENABLE_TAO  ((uint8_t) 1)
#define CANARD_INTERNAL_DISABLE_TAO ((uint8_t) 0)

#if defined(__GNUC__)
# define CANARD_MAYBE_UNUSED(x) x __attribute__((unused))
#else
# define CANARD_MAYBE_UNUSED(x) x
#endif

/**
  * @brief dsdl_uavcan_protocol_dynamic_node_id_server_Entry_encode_internal
  * @param source : pointer to source data struct
  * @param msg_buf: pointer to msg storage
  * @param offset: bit offset to msg storage
  * @param root_item: for detecting if TAO should be used
  * @retval returns offset
  */
uint32_t dsdl_uavcan_protocol_dynamic_node_id_server_Entry_encode_internal(dsdl_uavcan_protocol_dynamic_node_id_server_Entry* source,
  void* msg_buf,
  uint32_t offset,
  uint8_t CANARD_MAYBE_UNUSED(root_item))
{
    uint32_t c = 0;

    canardEncodeScalar(msg_buf, offset, 32, (void*)&source->term); // 4294967295
    offset += 32;

    // Static array (unique_id)
    for (c = 0; c < 16; c++)
    {
        canardEncodeScalar(msg_buf, offset, 8, (void*)(source->unique_id + c)); // 255
        offset += 8;
    }

    // Void1
    offset += 1;
    source->node_id = CANARD_INTERNAL_SATURATE_UNSIGNED(source->node_id, 127)
    canardEncodeScalar(msg_buf, offset, 7, (void*)&source->node_id); // 127
    offset += 7;

    return offset;
}

/**
  * @brief dsdl_uavcan_protocol_dynamic_node_id_server_Entry_encode
  * @param source : Pointer to source data struct
  * @param msg_buf: Pointer to msg storage
  * @retval returns message length as bytes
  */
uint32_t dsdl_uavcan_protocol_dynamic_node_id_server_Entry_encode(dsdl_uavcan_protocol_dynamic_node_id_server_Entry* source, void* msg_buf)
{
    uint32_t offset = 0;

    offset = dsdl_uavcan_protocol_dynamic_node_id_server_Entry_encode_internal(source, msg_buf, offset, 1);

    return (offset + 7 ) / 8;
}

/**
  * @brief dsdl_uavcan_protocol_dynamic_node_id_server_Entry_decode_internal
  * @param transfer: Pointer to CanardRxTransfer transfer
  * @param payload_len: Payload message length
  * @param dest: Pointer to destination struct
  * @param dyn_arr_buf: NULL or Pointer to memory storage to be used for dynamic arrays
  *                     dsdl_uavcan_protocol_dynamic_node_id_server_Entry dyn memory will point to dyn_arr_buf memory.
  *                     NULL will ignore dynamic arrays decoding.
  * @param offset: Call with 0, bit offset to msg storage
  * @param tao: is tail array optimization used
  * @retval offset or ERROR value if < 0
  */
int32_t dsdl_uavcan_protocol_dynamic_node_id_server_Entry_decode_internal(
  const CanardRxTransfer* transfer,
  uint16_t CANARD_MAYBE_UNUSED(payload_len),
  dsdl_uavcan_protocol_dynamic_node_id_server_Entry* dest,
  uint8_t** CANARD_MAYBE_UNUSED(dyn_arr_buf),
  int32_t offset,
  uint8_t CANARD_MAYBE_UNUSED(tao))
{
    int32_t ret = 0;
    uint32_t c = 0;

    ret = canardDecodeScalar(transfer, offset, 32, false, (void*)&dest->term);
    if (ret != 32)
    {
        goto dsdl_uavcan_protocol_dynamic_node_id_server_Entry_error_exit;
    }
    offset += 32;

    // Static array (unique_id)
    for (c = 0; c < 16; c++)
    {
        ret = canardDecodeScalar(transfer, offset, 8, false, (void*)(dest->unique_id + c));
        if (ret != 8)
        {
            goto dsdl_uavcan_protocol_dynamic_node_id_server_Entry_error_exit;
        }
        offset += 8;
    }

    // Void1
    offset += 1;

    ret = canardDecodeScalar(transfer, offset, 7, false, (void*)&dest->node_id);
    if (ret != 7)
    {
        goto dsdl_uavcan_protocol_dynamic_node_id_server_Entry_error_exit;
    }
    offset += 7;
    return offset;

dsdl_uavcan_protocol_dynamic_node_id_server_Entry_error_exit:
    if (ret < 0)
    {
        return ret;
    }
    else
    {
        return -CANARD_ERROR_INTERNAL;
    }
}

/**
  * @brief dsdl_uavcan_protocol_dynamic_node_id_server_Entry_decode
  * @param transfer: Pointer to CanardRxTransfer transfer
  * @param payload_len: Payload message length
  * @param dest: Pointer to destination struct
  * @param dyn_arr_buf: NULL or Pointer to memory storage to be used for dynamic arrays
  *                     dsdl_uavcan_protocol_dynamic_node_id_server_Entry dyn memory will point to dyn_arr_buf memory.
  *                     NULL will ignore dynamic arrays decoding.
  * @retval offset or ERROR value if < 0
  */
int32_t dsdl_uavcan_protocol_dynamic_node_id_server_Entry_decode(const CanardRxTransfer* transfer,
  uint16_t payload_len,
  dsdl_uavcan_protocol_dynamic_node_id_server_Entry* dest,
  uint8_t** dyn_arr_buf)
{
    const int32_t offset = 0;
    int32_t ret = 0;

    /* Backward compatibility support for removing TAO
     *  - first try to decode with TAO DISABLED
     *  - if it fails fall back to TAO ENABLED
     */
    uint8_t tao = CANARD_INTERNAL_DISABLE_TAO;

    while (1)
    {
        // Clear the destination struct
        for (uint32_t c = 0; c < sizeof(dsdl_uavcan_protocol_dynamic_node_id_server_Entry); c++)
        {
            ((uint8_t*)dest)[c] = 0x00;
        }

        ret = dsdl_uavcan_protocol_dynamic_node_id_server_Entry_decode_internal(transfer, payload_len, dest, dyn_arr_buf, offset, tao);

        if (ret >= 0)
        {
            break;
        }

        if (tao == CANARD_INTERNAL_ENABLE_TAO)
        {
            break;
        }
        tao = CANARD_INTERNAL_ENABLE_TAO;
    }

    return ret;
}

#ifdef __cplusplus
} // extern "C"
#endif
#endif // __DSDL_UAVCAN_PROTOCOL_DYNAMIC_NODE_ID_SERVER_ENTRY