/*
 * UAVCAN data structure definition for libcanard.
 *
 * Autogenerated, do not edit.
 *
 */

#ifndef __DSDL_UAVCAN_COARSEORIENTATION
#define __DSDL_UAVCAN_COARSEORIENTATION

#include <uavcan_service/libcanard/canard.h>

#ifdef __cplusplus
extern "C"
{
#endif

/******************************* Source text **********************************
#
# Nested type.
# Coarse, low-resolution 3D orientation represented as fixed axes in 16 bit.
#
# Roll, pitch, yaw angles in radians should be multiplied by
# ANGLE_MULTIPLIER in order to convert them to the coarse representation.
#
# ANGLE_MULTIPLIER = NORM / PI
#
# Where NORM is 12, because it:
#  - Fits the maximum range of a signed 5 bit integer
#  - Allows to exactly represent the following angles:
#    0, 15, 30, 45, 60, 75, 90, 105, 120, 135, 150, 165, 180, and negatives
#

float32 ANGLE_MULTIPLIER = 4.7746482927568605

int5[3] fixed_axis_roll_pitch_yaw

bool orientation_defined    # False if the orientation is actually not defined
******************************************************************************/

/********************* DSDL signature source definition ***********************
dsdl.uavcan.CoarseOrientation
saturated int5[3] fixed_axis_roll_pitch_yaw
saturated bool orientation_defined
******************************************************************************/

#define DSDL_UAVCAN_COARSEORIENTATION_NAME                 "dsdl.uavcan.CoarseOrientation"
#define DSDL_UAVCAN_COARSEORIENTATION_SIGNATURE            (0xEE52CA438CC09139ULL)

#define DSDL_UAVCAN_COARSEORIENTATION_MAX_SIZE             ((16 + 7)/8)

// Constants
#define DSDL_UAVCAN_COARSEORIENTATION_ANGLE_MULTIPLIER               4.7746482927568605 // 4.7746482927568605

#define DSDL_UAVCAN_COARSEORIENTATION_FIXED_AXIS_ROLL_PITCH_YAW_LENGTH                   3

typedef struct
{
    // FieldTypes
    int8_t     fixed_axis_roll_pitch_yaw[3];  // Static Array 5bit[3] max items
    bool       orientation_defined;           // bit len 1

} dsdl_uavcan_CoarseOrientation;

static inline
uint32_t dsdl_uavcan_CoarseOrientation_encode(dsdl_uavcan_CoarseOrientation* source, void* msg_buf);

static inline
int32_t dsdl_uavcan_CoarseOrientation_decode(const CanardRxTransfer* transfer, uint16_t payload_len, dsdl_uavcan_CoarseOrientation* dest, uint8_t** dyn_arr_buf);

static inline
uint32_t dsdl_uavcan_CoarseOrientation_encode_internal(dsdl_uavcan_CoarseOrientation* source, void* msg_buf, uint32_t offset, uint8_t root_item);

static inline
int32_t dsdl_uavcan_CoarseOrientation_decode_internal(const CanardRxTransfer* transfer, uint16_t payload_len, dsdl_uavcan_CoarseOrientation* dest, uint8_t** dyn_arr_buf, int32_t offset, uint8_t tao);

/*
 * UAVCAN data structure definition for libcanard.
 *
 * Autogenerated, do not edit.
 *
 */

#ifndef CANARD_INTERNAL_SATURATE
#define CANARD_INTERNAL_SATURATE(x, max) ( ((x) > max) ? max : ( (-(x) > max) ? (-max) : (x) ) );
#endif

#ifndef CANARD_INTERNAL_SATURATE_UNSIGNED
#define CANARD_INTERNAL_SATURATE_UNSIGNED(x, max) ( ((x) > max) ? max : (x) );
#endif

#define CANARD_INTERNAL_ENABLE_TAO  ((uint8_t) 1)
#define CANARD_INTERNAL_DISABLE_TAO ((uint8_t) 0)

#if defined(__GNUC__)
# define CANARD_MAYBE_UNUSED(x) x __attribute__((unused))
#else
# define CANARD_MAYBE_UNUSED(x) x
#endif

/**
  * @brief dsdl_uavcan_CoarseOrientation_encode_internal
  * @param source : pointer to source data struct
  * @param msg_buf: pointer to msg storage
  * @param offset: bit offset to msg storage
  * @param root_item: for detecting if TAO should be used
  * @retval returns offset
  */
uint32_t dsdl_uavcan_CoarseOrientation_encode_internal(dsdl_uavcan_CoarseOrientation* source,
  void* msg_buf,
  uint32_t offset,
  uint8_t CANARD_MAYBE_UNUSED(root_item))
{
    uint32_t c = 0;

    // Static array (fixed_axis_roll_pitch_yaw)
    for (c = 0; c < 3; c++)
    {
        canardEncodeScalar(msg_buf, offset, 5, (void*)(source->fixed_axis_roll_pitch_yaw + c)); // 15
        offset += 5;
    }

    source->orientation_defined = CANARD_INTERNAL_SATURATE_UNSIGNED(source->orientation_defined, 0)
    canardEncodeScalar(msg_buf, offset, 1, (void*)&source->orientation_defined); // 0
    offset += 1;

    return offset;
}

/**
  * @brief dsdl_uavcan_CoarseOrientation_encode
  * @param source : Pointer to source data struct
  * @param msg_buf: Pointer to msg storage
  * @retval returns message length as bytes
  */
uint32_t dsdl_uavcan_CoarseOrientation_encode(dsdl_uavcan_CoarseOrientation* source, void* msg_buf)
{
    uint32_t offset = 0;

    offset = dsdl_uavcan_CoarseOrientation_encode_internal(source, msg_buf, offset, 1);

    return (offset + 7 ) / 8;
}

/**
  * @brief dsdl_uavcan_CoarseOrientation_decode_internal
  * @param transfer: Pointer to CanardRxTransfer transfer
  * @param payload_len: Payload message length
  * @param dest: Pointer to destination struct
  * @param dyn_arr_buf: NULL or Pointer to memory storage to be used for dynamic arrays
  *                     dsdl_uavcan_CoarseOrientation dyn memory will point to dyn_arr_buf memory.
  *                     NULL will ignore dynamic arrays decoding.
  * @param offset: Call with 0, bit offset to msg storage
  * @param tao: is tail array optimization used
  * @retval offset or ERROR value if < 0
  */
int32_t dsdl_uavcan_CoarseOrientation_decode_internal(
  const CanardRxTransfer* transfer,
  uint16_t CANARD_MAYBE_UNUSED(payload_len),
  dsdl_uavcan_CoarseOrientation* dest,
  uint8_t** CANARD_MAYBE_UNUSED(dyn_arr_buf),
  int32_t offset,
  uint8_t CANARD_MAYBE_UNUSED(tao))
{
    int32_t ret = 0;
    uint32_t c = 0;

    // Static array (fixed_axis_roll_pitch_yaw)
    for (c = 0; c < 3; c++)
    {
        ret = canardDecodeScalar(transfer, offset, 5, true, (void*)(dest->fixed_axis_roll_pitch_yaw + c));
        if (ret != 5)
        {
            goto dsdl_uavcan_CoarseOrientation_error_exit;
        }
        offset += 5;
    }

    ret = canardDecodeScalar(transfer, offset, 1, false, (void*)&dest->orientation_defined);
    if (ret != 1)
    {
        goto dsdl_uavcan_CoarseOrientation_error_exit;
    }
    offset += 1;
    return offset;

dsdl_uavcan_CoarseOrientation_error_exit:
    if (ret < 0)
    {
        return ret;
    }
    else
    {
        return -CANARD_ERROR_INTERNAL;
    }
}

/**
  * @brief dsdl_uavcan_CoarseOrientation_decode
  * @param transfer: Pointer to CanardRxTransfer transfer
  * @param payload_len: Payload message length
  * @param dest: Pointer to destination struct
  * @param dyn_arr_buf: NULL or Pointer to memory storage to be used for dynamic arrays
  *                     dsdl_uavcan_CoarseOrientation dyn memory will point to dyn_arr_buf memory.
  *                     NULL will ignore dynamic arrays decoding.
  * @retval offset or ERROR value if < 0
  */
int32_t dsdl_uavcan_CoarseOrientation_decode(const CanardRxTransfer* transfer,
  uint16_t payload_len,
  dsdl_uavcan_CoarseOrientation* dest,
  uint8_t** dyn_arr_buf)
{
    const int32_t offset = 0;
    int32_t ret = 0;

    /* Backward compatibility support for removing TAO
     *  - first try to decode with TAO DISABLED
     *  - if it fails fall back to TAO ENABLED
     */
    uint8_t tao = CANARD_INTERNAL_DISABLE_TAO;

    while (1)
    {
        // Clear the destination struct
        for (uint32_t c = 0; c < sizeof(dsdl_uavcan_CoarseOrientation); c++)
        {
            ((uint8_t*)dest)[c] = 0x00;
        }

        ret = dsdl_uavcan_CoarseOrientation_decode_internal(transfer, payload_len, dest, dyn_arr_buf, offset, tao);

        if (ret >= 0)
        {
            break;
        }

        if (tao == CANARD_INTERNAL_ENABLE_TAO)
        {
            break;
        }
        tao = CANARD_INTERNAL_ENABLE_TAO;
    }

    return ret;
}

#ifdef __cplusplus
} // extern "C"
#endif
#endif // __DSDL_UAVCAN_COARSEORIENTATION