/*
 * UAVCAN data structure definition for libcanard.
 *
 * Autogenerated, do not edit.
 *
 */

#ifndef __DSDL_UAVCAN_TUNNEL_BROADCAST
#define __DSDL_UAVCAN_TUNNEL_BROADCAST

#include <uavcan_service/libcanard/canard.h>

#ifdef __cplusplus
extern "C"
{
#endif

#include <dsdl/uavcan/tunnel/Protocol.h>

/******************************* Source text **********************************
#
# This message struct carries arbitrary data in the format of the specified high-level protocol.
# The data will be delivered to all nodes that are interested in tunneled protocols.
# Finer addressing schemes may be implemented using the means provided by the encapsulated protocol.
# The channelID allows for additional routing between the source and target nodes.

Protocol protocol
uint8 channel_id

uint8[<=60] buffer    # TAO rules apply
******************************************************************************/

/********************* DSDL signature source definition ***********************
dsdl.uavcan.tunnel.Broadcast
dsdl.uavcan.tunnel.Protocol protocol
saturated uint8 channel_id
saturated uint8[<=60] buffer
******************************************************************************/

#define DSDL_UAVCAN_TUNNEL_BROADCAST_ID                    2010
#define DSDL_UAVCAN_TUNNEL_BROADCAST_NAME                  "dsdl.uavcan.tunnel.Broadcast"
#define DSDL_UAVCAN_TUNNEL_BROADCAST_SIGNATURE             (0x7F8D9D29422F087ULL)

#define DSDL_UAVCAN_TUNNEL_BROADCAST_MAX_SIZE              ((502 + 7)/8)

// Constants

#define DSDL_UAVCAN_TUNNEL_BROADCAST_BUFFER_MAX_LENGTH                                   60

typedef struct
{
    // FieldTypes
    dsdl_uavcan_tunnel_Protocol protocol;                      //
    uint8_t    channel_id;                    // bit len 8
    struct
    {
        uint8_t    len;                       // Dynamic array length
        uint8_t*   data;                      // Dynamic Array 8bit[60] max items
    } buffer;

} dsdl_uavcan_tunnel_Broadcast;

static inline
uint32_t dsdl_uavcan_tunnel_Broadcast_encode(dsdl_uavcan_tunnel_Broadcast* source, void* msg_buf);

static inline
int32_t dsdl_uavcan_tunnel_Broadcast_decode(const CanardRxTransfer* transfer, uint16_t payload_len, dsdl_uavcan_tunnel_Broadcast* dest, uint8_t** dyn_arr_buf);

static inline
uint32_t dsdl_uavcan_tunnel_Broadcast_encode_internal(dsdl_uavcan_tunnel_Broadcast* source, void* msg_buf, uint32_t offset, uint8_t root_item);

static inline
int32_t dsdl_uavcan_tunnel_Broadcast_decode_internal(const CanardRxTransfer* transfer, uint16_t payload_len, dsdl_uavcan_tunnel_Broadcast* dest, uint8_t** dyn_arr_buf, int32_t offset, uint8_t tao);

/*
 * UAVCAN data structure definition for libcanard.
 *
 * Autogenerated, do not edit.
 *
 */

#ifndef CANARD_INTERNAL_SATURATE
#define CANARD_INTERNAL_SATURATE(x, max) ( ((x) > max) ? max : ( (-(x) > max) ? (-max) : (x) ) );
#endif

#ifndef CANARD_INTERNAL_SATURATE_UNSIGNED
#define CANARD_INTERNAL_SATURATE_UNSIGNED(x, max) ( ((x) > max) ? max : (x) );
#endif

#define CANARD_INTERNAL_ENABLE_TAO  ((uint8_t) 1)
#define CANARD_INTERNAL_DISABLE_TAO ((uint8_t) 0)

#if defined(__GNUC__)
# define CANARD_MAYBE_UNUSED(x) x __attribute__((unused))
#else
# define CANARD_MAYBE_UNUSED(x) x
#endif

/**
  * @brief dsdl_uavcan_tunnel_Broadcast_encode_internal
  * @param source : pointer to source data struct
  * @param msg_buf: pointer to msg storage
  * @param offset: bit offset to msg storage
  * @param root_item: for detecting if TAO should be used
  * @retval returns offset
  */
uint32_t dsdl_uavcan_tunnel_Broadcast_encode_internal(dsdl_uavcan_tunnel_Broadcast* source,
  void* msg_buf,
  uint32_t offset,
  uint8_t CANARD_MAYBE_UNUSED(root_item))
{
    uint32_t c = 0;

    // Compound
    offset = dsdl_uavcan_tunnel_Protocol_encode_internal((void*)&source->protocol, msg_buf, offset, 0);
    canardEncodeScalar(msg_buf, offset, 8, (void*)&source->channel_id); // 255
    offset += 8;

    // Dynamic Array (buffer)
    if (! root_item)
    {
        // - Add array length
        canardEncodeScalar(msg_buf, offset, 6, (void*)&source->buffer.len);
        offset += 6;
    }

    // - Add array items
    for (c = 0; c < source->buffer.len; c++)
    {
        canardEncodeScalar(msg_buf,
                           offset,
                           8,
                           (void*)(source->buffer.data + c));// 255
        offset += 8;
    }

    return offset;
}

/**
  * @brief dsdl_uavcan_tunnel_Broadcast_encode
  * @param source : Pointer to source data struct
  * @param msg_buf: Pointer to msg storage
  * @retval returns message length as bytes
  */
uint32_t dsdl_uavcan_tunnel_Broadcast_encode(dsdl_uavcan_tunnel_Broadcast* source, void* msg_buf)
{
    uint32_t offset = 0;

    offset = dsdl_uavcan_tunnel_Broadcast_encode_internal(source, msg_buf, offset, 1);

    return (offset + 7 ) / 8;
}

/**
  * @brief dsdl_uavcan_tunnel_Broadcast_decode_internal
  * @param transfer: Pointer to CanardRxTransfer transfer
  * @param payload_len: Payload message length
  * @param dest: Pointer to destination struct
  * @param dyn_arr_buf: NULL or Pointer to memory storage to be used for dynamic arrays
  *                     dsdl_uavcan_tunnel_Broadcast dyn memory will point to dyn_arr_buf memory.
  *                     NULL will ignore dynamic arrays decoding.
  * @param offset: Call with 0, bit offset to msg storage
  * @param tao: is tail array optimization used
  * @retval offset or ERROR value if < 0
  */
int32_t dsdl_uavcan_tunnel_Broadcast_decode_internal(
  const CanardRxTransfer* transfer,
  uint16_t CANARD_MAYBE_UNUSED(payload_len),
  dsdl_uavcan_tunnel_Broadcast* dest,
  uint8_t** CANARD_MAYBE_UNUSED(dyn_arr_buf),
  int32_t offset,
  uint8_t CANARD_MAYBE_UNUSED(tao))
{
    int32_t ret = 0;
    uint32_t c = 0;

    // Compound
    offset = dsdl_uavcan_tunnel_Protocol_decode_internal(transfer, 0, (void*)&dest->protocol, dyn_arr_buf, offset, tao);
    if (offset < 0)
    {
        ret = offset;
        goto dsdl_uavcan_tunnel_Broadcast_error_exit;
    }

    ret = canardDecodeScalar(transfer, offset, 8, false, (void*)&dest->channel_id);
    if (ret != 8)
    {
        goto dsdl_uavcan_tunnel_Broadcast_error_exit;
    }
    offset += 8;

    // Dynamic Array (buffer)
    //  - Last item in struct & Root item & (Array Size > 8 bit), tail array optimization
    if (payload_len && tao == CANARD_INTERNAL_ENABLE_TAO)
    {
        //  - Calculate Array length from MSG length
        dest->buffer.len = ((payload_len * 8) - offset ) / 8; // 8 bit array item size
    }
    else
    {
        // - Array length 6 bits
        ret = canardDecodeScalar(transfer,
                                 offset,
                                 6,
                                 false,
                                 (void*)&dest->buffer.len); // 255
        if (ret != 6)
        {
            goto dsdl_uavcan_tunnel_Broadcast_error_exit;
        }
        offset += 6;
    }

    //  - Get Array
    if (dyn_arr_buf)
    {
        dest->buffer.data = (uint8_t*)*dyn_arr_buf;
    }

    for (c = 0; c < dest->buffer.len; c++)
    {
        if (dyn_arr_buf)
        {
            ret = canardDecodeScalar(transfer,
                                     offset,
                                     8,
                                     false,
                                     (void*)*dyn_arr_buf); // 255
            if (ret != 8)
            {
                goto dsdl_uavcan_tunnel_Broadcast_error_exit;
            }
            *dyn_arr_buf = (uint8_t*)(((uint8_t*)*dyn_arr_buf) + 1);
        }
        offset += 8;
    }
    return offset;

dsdl_uavcan_tunnel_Broadcast_error_exit:
    if (ret < 0)
    {
        return ret;
    }
    else
    {
        return -CANARD_ERROR_INTERNAL;
    }
}

/**
  * @brief dsdl_uavcan_tunnel_Broadcast_decode
  * @param transfer: Pointer to CanardRxTransfer transfer
  * @param payload_len: Payload message length
  * @param dest: Pointer to destination struct
  * @param dyn_arr_buf: NULL or Pointer to memory storage to be used for dynamic arrays
  *                     dsdl_uavcan_tunnel_Broadcast dyn memory will point to dyn_arr_buf memory.
  *                     NULL will ignore dynamic arrays decoding.
  * @retval offset or ERROR value if < 0
  */
int32_t dsdl_uavcan_tunnel_Broadcast_decode(const CanardRxTransfer* transfer,
  uint16_t payload_len,
  dsdl_uavcan_tunnel_Broadcast* dest,
  uint8_t** dyn_arr_buf)
{
    const int32_t offset = 0;
    int32_t ret = 0;

    /* Backward compatibility support for removing TAO
     *  - first try to decode with TAO DISABLED
     *  - if it fails fall back to TAO ENABLED
     */
    uint8_t tao = CANARD_INTERNAL_DISABLE_TAO;

    while (1)
    {
        // Clear the destination struct
        for (uint32_t c = 0; c < sizeof(dsdl_uavcan_tunnel_Broadcast); c++)
        {
            ((uint8_t*)dest)[c] = 0x00;
        }

        ret = dsdl_uavcan_tunnel_Broadcast_decode_internal(transfer, payload_len, dest, dyn_arr_buf, offset, tao);

        if (ret >= 0)
        {
            break;
        }

        if (tao == CANARD_INTERNAL_ENABLE_TAO)
        {
            break;
        }
        tao = CANARD_INTERNAL_ENABLE_TAO;
    }

    return ret;
}

#ifdef __cplusplus
} // extern "C"
#endif
#endif // __DSDL_UAVCAN_TUNNEL_BROADCAST