/*
 * UAVCAN data structure definition for libcanard.
 *
 * Autogenerated, do not edit.
 *
 */

#ifndef __DSDL_UAVCAN_EQUIPMENT_GNSS_AUXILIARY
#define __DSDL_UAVCAN_EQUIPMENT_GNSS_AUXILIARY

#include <uavcan_service/libcanard/canard.h>

#ifdef __cplusplus
extern "C"
{
#endif

/******************************* Source text **********************************
#
# GNSS low priority auxiliary info.
# Unknown DOP parameters should be set to NAN.
#

float16 gdop
float16 pdop
float16 hdop
float16 vdop
float16 tdop
float16 ndop
float16 edop

uint7 sats_visible                    # All visible sats of all available GNSS (e.g. GPS, GLONASS, etc)
uint6 sats_used                       # All used sats of all available GNSS
******************************************************************************/

/********************* DSDL signature source definition ***********************
dsdl.uavcan.equipment.gnss.Auxiliary
saturated float16 gdop
saturated float16 pdop
saturated float16 hdop
saturated float16 vdop
saturated float16 tdop
saturated float16 ndop
saturated float16 edop
saturated uint7 sats_visible
saturated uint6 sats_used
******************************************************************************/

#define DSDL_UAVCAN_EQUIPMENT_GNSS_AUXILIARY_ID            1061
#define DSDL_UAVCAN_EQUIPMENT_GNSS_AUXILIARY_NAME          "dsdl.uavcan.equipment.gnss.Auxiliary"
#define DSDL_UAVCAN_EQUIPMENT_GNSS_AUXILIARY_SIGNATURE     (0x7278E2D3125AAE5ULL)

#define DSDL_UAVCAN_EQUIPMENT_GNSS_AUXILIARY_MAX_SIZE      ((125 + 7)/8)

// Constants

typedef struct
{
    // FieldTypes
    float      gdop;                          // float16 Saturate
    float      pdop;                          // float16 Saturate
    float      hdop;                          // float16 Saturate
    float      vdop;                          // float16 Saturate
    float      tdop;                          // float16 Saturate
    float      ndop;                          // float16 Saturate
    float      edop;                          // float16 Saturate
    uint8_t    sats_visible;                  // bit len 7
    uint8_t    sats_used;                     // bit len 6

} dsdl_uavcan_equipment_gnss_Auxiliary;

static inline
uint32_t dsdl_uavcan_equipment_gnss_Auxiliary_encode(dsdl_uavcan_equipment_gnss_Auxiliary* source, void* msg_buf);

static inline
int32_t dsdl_uavcan_equipment_gnss_Auxiliary_decode(const CanardRxTransfer* transfer, uint16_t payload_len, dsdl_uavcan_equipment_gnss_Auxiliary* dest, uint8_t** dyn_arr_buf);

static inline
uint32_t dsdl_uavcan_equipment_gnss_Auxiliary_encode_internal(dsdl_uavcan_equipment_gnss_Auxiliary* source, void* msg_buf, uint32_t offset, uint8_t root_item);

static inline
int32_t dsdl_uavcan_equipment_gnss_Auxiliary_decode_internal(const CanardRxTransfer* transfer, uint16_t payload_len, dsdl_uavcan_equipment_gnss_Auxiliary* dest, uint8_t** dyn_arr_buf, int32_t offset, uint8_t tao);

/*
 * UAVCAN data structure definition for libcanard.
 *
 * Autogenerated, do not edit.
 *
 */

#ifndef CANARD_INTERNAL_SATURATE
#define CANARD_INTERNAL_SATURATE(x, max) ( ((x) > max) ? max : ( (-(x) > max) ? (-max) : (x) ) );
#endif

#ifndef CANARD_INTERNAL_SATURATE_UNSIGNED
#define CANARD_INTERNAL_SATURATE_UNSIGNED(x, max) ( ((x) > max) ? max : (x) );
#endif

#define CANARD_INTERNAL_ENABLE_TAO  ((uint8_t) 1)
#define CANARD_INTERNAL_DISABLE_TAO ((uint8_t) 0)

#if defined(__GNUC__)
# define CANARD_MAYBE_UNUSED(x) x __attribute__((unused))
#else
# define CANARD_MAYBE_UNUSED(x) x
#endif

/**
  * @brief dsdl_uavcan_equipment_gnss_Auxiliary_encode_internal
  * @param source : pointer to source data struct
  * @param msg_buf: pointer to msg storage
  * @param offset: bit offset to msg storage
  * @param root_item: for detecting if TAO should be used
  * @retval returns offset
  */
uint32_t dsdl_uavcan_equipment_gnss_Auxiliary_encode_internal(dsdl_uavcan_equipment_gnss_Auxiliary* source,
  void* msg_buf,
  uint32_t offset,
  uint8_t CANARD_MAYBE_UNUSED(root_item))
{
#ifndef CANARD_USE_FLOAT16_CAST
    uint16_t tmp_float = 0;
#else
    CANARD_USE_FLOAT16_CAST tmp_float = 0;
#endif

    // float16 special handling
#ifndef CANARD_USE_FLOAT16_CAST
    tmp_float = canardConvertNativeFloatToFloat16(source->gdop);
#else
    tmp_float = (CANARD_USE_FLOAT16_CAST)source->gdop;
#endif
    canardEncodeScalar(msg_buf, offset, 16, (void*)&tmp_float); // 32767
    offset += 16;

    // float16 special handling
#ifndef CANARD_USE_FLOAT16_CAST
    tmp_float = canardConvertNativeFloatToFloat16(source->pdop);
#else
    tmp_float = (CANARD_USE_FLOAT16_CAST)source->pdop;
#endif
    canardEncodeScalar(msg_buf, offset, 16, (void*)&tmp_float); // 32767
    offset += 16;

    // float16 special handling
#ifndef CANARD_USE_FLOAT16_CAST
    tmp_float = canardConvertNativeFloatToFloat16(source->hdop);
#else
    tmp_float = (CANARD_USE_FLOAT16_CAST)source->hdop;
#endif
    canardEncodeScalar(msg_buf, offset, 16, (void*)&tmp_float); // 32767
    offset += 16;

    // float16 special handling
#ifndef CANARD_USE_FLOAT16_CAST
    tmp_float = canardConvertNativeFloatToFloat16(source->vdop);
#else
    tmp_float = (CANARD_USE_FLOAT16_CAST)source->vdop;
#endif
    canardEncodeScalar(msg_buf, offset, 16, (void*)&tmp_float); // 32767
    offset += 16;

    // float16 special handling
#ifndef CANARD_USE_FLOAT16_CAST
    tmp_float = canardConvertNativeFloatToFloat16(source->tdop);
#else
    tmp_float = (CANARD_USE_FLOAT16_CAST)source->tdop;
#endif
    canardEncodeScalar(msg_buf, offset, 16, (void*)&tmp_float); // 32767
    offset += 16;

    // float16 special handling
#ifndef CANARD_USE_FLOAT16_CAST
    tmp_float = canardConvertNativeFloatToFloat16(source->ndop);
#else
    tmp_float = (CANARD_USE_FLOAT16_CAST)source->ndop;
#endif
    canardEncodeScalar(msg_buf, offset, 16, (void*)&tmp_float); // 32767
    offset += 16;

    // float16 special handling
#ifndef CANARD_USE_FLOAT16_CAST
    tmp_float = canardConvertNativeFloatToFloat16(source->edop);
#else
    tmp_float = (CANARD_USE_FLOAT16_CAST)source->edop;
#endif
    canardEncodeScalar(msg_buf, offset, 16, (void*)&tmp_float); // 32767
    offset += 16;
    source->sats_visible = CANARD_INTERNAL_SATURATE_UNSIGNED(source->sats_visible, 127)
    canardEncodeScalar(msg_buf, offset, 7, (void*)&source->sats_visible); // 127
    offset += 7;

    source->sats_used = CANARD_INTERNAL_SATURATE_UNSIGNED(source->sats_used, 63)
    canardEncodeScalar(msg_buf, offset, 6, (void*)&source->sats_used); // 63
    offset += 6;

    return offset;
}

/**
  * @brief dsdl_uavcan_equipment_gnss_Auxiliary_encode
  * @param source : Pointer to source data struct
  * @param msg_buf: Pointer to msg storage
  * @retval returns message length as bytes
  */
uint32_t dsdl_uavcan_equipment_gnss_Auxiliary_encode(dsdl_uavcan_equipment_gnss_Auxiliary* source, void* msg_buf)
{
    uint32_t offset = 0;

    offset = dsdl_uavcan_equipment_gnss_Auxiliary_encode_internal(source, msg_buf, offset, 1);

    return (offset + 7 ) / 8;
}

/**
  * @brief dsdl_uavcan_equipment_gnss_Auxiliary_decode_internal
  * @param transfer: Pointer to CanardRxTransfer transfer
  * @param payload_len: Payload message length
  * @param dest: Pointer to destination struct
  * @param dyn_arr_buf: NULL or Pointer to memory storage to be used for dynamic arrays
  *                     dsdl_uavcan_equipment_gnss_Auxiliary dyn memory will point to dyn_arr_buf memory.
  *                     NULL will ignore dynamic arrays decoding.
  * @param offset: Call with 0, bit offset to msg storage
  * @param tao: is tail array optimization used
  * @retval offset or ERROR value if < 0
  */
int32_t dsdl_uavcan_equipment_gnss_Auxiliary_decode_internal(
  const CanardRxTransfer* transfer,
  uint16_t CANARD_MAYBE_UNUSED(payload_len),
  dsdl_uavcan_equipment_gnss_Auxiliary* dest,
  uint8_t** CANARD_MAYBE_UNUSED(dyn_arr_buf),
  int32_t offset,
  uint8_t CANARD_MAYBE_UNUSED(tao))
{
    int32_t ret = 0;
#ifndef CANARD_USE_FLOAT16_CAST
    uint16_t tmp_float = 0;
#else
    CANARD_USE_FLOAT16_CAST tmp_float = 0;
#endif

    // float16 special handling
    ret = canardDecodeScalar(transfer, offset, 16, false, (void*)&tmp_float);

    if (ret != 16)
    {
        goto dsdl_uavcan_equipment_gnss_Auxiliary_error_exit;
    }
#ifndef CANARD_USE_FLOAT16_CAST
    dest->gdop = canardConvertFloat16ToNativeFloat(tmp_float);
#else
    dest->gdop = (float)tmp_float;
#endif
    offset += 16;

    // float16 special handling
    ret = canardDecodeScalar(transfer, offset, 16, false, (void*)&tmp_float);

    if (ret != 16)
    {
        goto dsdl_uavcan_equipment_gnss_Auxiliary_error_exit;
    }
#ifndef CANARD_USE_FLOAT16_CAST
    dest->pdop = canardConvertFloat16ToNativeFloat(tmp_float);
#else
    dest->pdop = (float)tmp_float;
#endif
    offset += 16;

    // float16 special handling
    ret = canardDecodeScalar(transfer, offset, 16, false, (void*)&tmp_float);

    if (ret != 16)
    {
        goto dsdl_uavcan_equipment_gnss_Auxiliary_error_exit;
    }
#ifndef CANARD_USE_FLOAT16_CAST
    dest->hdop = canardConvertFloat16ToNativeFloat(tmp_float);
#else
    dest->hdop = (float)tmp_float;
#endif
    offset += 16;

    // float16 special handling
    ret = canardDecodeScalar(transfer, offset, 16, false, (void*)&tmp_float);

    if (ret != 16)
    {
        goto dsdl_uavcan_equipment_gnss_Auxiliary_error_exit;
    }
#ifndef CANARD_USE_FLOAT16_CAST
    dest->vdop = canardConvertFloat16ToNativeFloat(tmp_float);
#else
    dest->vdop = (float)tmp_float;
#endif
    offset += 16;

    // float16 special handling
    ret = canardDecodeScalar(transfer, offset, 16, false, (void*)&tmp_float);

    if (ret != 16)
    {
        goto dsdl_uavcan_equipment_gnss_Auxiliary_error_exit;
    }
#ifndef CANARD_USE_FLOAT16_CAST
    dest->tdop = canardConvertFloat16ToNativeFloat(tmp_float);
#else
    dest->tdop = (float)tmp_float;
#endif
    offset += 16;

    // float16 special handling
    ret = canardDecodeScalar(transfer, offset, 16, false, (void*)&tmp_float);

    if (ret != 16)
    {
        goto dsdl_uavcan_equipment_gnss_Auxiliary_error_exit;
    }
#ifndef CANARD_USE_FLOAT16_CAST
    dest->ndop = canardConvertFloat16ToNativeFloat(tmp_float);
#else
    dest->ndop = (float)tmp_float;
#endif
    offset += 16;

    // float16 special handling
    ret = canardDecodeScalar(transfer, offset, 16, false, (void*)&tmp_float);

    if (ret != 16)
    {
        goto dsdl_uavcan_equipment_gnss_Auxiliary_error_exit;
    }
#ifndef CANARD_USE_FLOAT16_CAST
    dest->edop = canardConvertFloat16ToNativeFloat(tmp_float);
#else
    dest->edop = (float)tmp_float;
#endif
    offset += 16;

    ret = canardDecodeScalar(transfer, offset, 7, false, (void*)&dest->sats_visible);
    if (ret != 7)
    {
        goto dsdl_uavcan_equipment_gnss_Auxiliary_error_exit;
    }
    offset += 7;

    ret = canardDecodeScalar(transfer, offset, 6, false, (void*)&dest->sats_used);
    if (ret != 6)
    {
        goto dsdl_uavcan_equipment_gnss_Auxiliary_error_exit;
    }
    offset += 6;
    return offset;

dsdl_uavcan_equipment_gnss_Auxiliary_error_exit:
    if (ret < 0)
    {
        return ret;
    }
    else
    {
        return -CANARD_ERROR_INTERNAL;
    }
}

/**
  * @brief dsdl_uavcan_equipment_gnss_Auxiliary_decode
  * @param transfer: Pointer to CanardRxTransfer transfer
  * @param payload_len: Payload message length
  * @param dest: Pointer to destination struct
  * @param dyn_arr_buf: NULL or Pointer to memory storage to be used for dynamic arrays
  *                     dsdl_uavcan_equipment_gnss_Auxiliary dyn memory will point to dyn_arr_buf memory.
  *                     NULL will ignore dynamic arrays decoding.
  * @retval offset or ERROR value if < 0
  */
int32_t dsdl_uavcan_equipment_gnss_Auxiliary_decode(const CanardRxTransfer* transfer,
  uint16_t payload_len,
  dsdl_uavcan_equipment_gnss_Auxiliary* dest,
  uint8_t** dyn_arr_buf)
{
    const int32_t offset = 0;
    int32_t ret = 0;

    /* Backward compatibility support for removing TAO
     *  - first try to decode with TAO DISABLED
     *  - if it fails fall back to TAO ENABLED
     */
    uint8_t tao = CANARD_INTERNAL_DISABLE_TAO;

    while (1)
    {
        // Clear the destination struct
        for (uint32_t c = 0; c < sizeof(dsdl_uavcan_equipment_gnss_Auxiliary); c++)
        {
            ((uint8_t*)dest)[c] = 0x00;
        }

        ret = dsdl_uavcan_equipment_gnss_Auxiliary_decode_internal(transfer, payload_len, dest, dyn_arr_buf, offset, tao);

        if (ret >= 0)
        {
            break;
        }

        if (tao == CANARD_INTERNAL_ENABLE_TAO)
        {
            break;
        }
        tao = CANARD_INTERNAL_ENABLE_TAO;
    }

    return ret;
}

#ifdef __cplusplus
} // extern "C"
#endif
#endif // __DSDL_UAVCAN_EQUIPMENT_GNSS_AUXILIARY